describe('Pruebas de Admin Post',()=>{
	beforeEach(()=>{
    		cy.visit('http://localhost:2368/ghost/#/signin')
			cy.get('#ember7').type('lucia.neme@gmail.com')
			cy.get('#ember9').type('Aforero.2o1o')
			cy.get('#ember11 > span').click()
			cy.wait(2000)
    	})

    	it('Listar post',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts')
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=draft')
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=scheduled')
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
	})	

    	it('Crear un post y no publicarlo',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts')
		cy.wait(2000)
		cy.contains('New post').click()
		cy.wait(2000)
		cy.get('textarea').type('Programar en C#') 
		cy.get('.koenig-editor__editor-wrapper').type('Prueba crear un post{enter}')
		cy.get('.gh-editor-back-button span').click()
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
		cy.contains('Programar en Python').should('be.visible')
		cy.wait(2000)
	})	
        
        it('Crear un post y publicarlo despues',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts')
		cy.wait(2000)
		cy.contains('New post').click()
		cy.wait(2000)
		cy.get('textarea').type('Programar en Python2') 
		cy.get('.koenig-editor__editor-wrapper').type('Prueba crear un post')
		cy.contains('Publish').click()
		cy.wait(2000)
                cy.get(':nth-child(2) > .gh-publishmenu-radio-button').click()
                cy.get('.gh-publishmenu-footer .gh-btn-icon span').click()
		cy.wait(2000)
		cy.get('.modal-footer .gh-btn:not(:first-child)').click()
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=scheduled')                
	})

	it('Crear un post Y publicarlo inmediatamente',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts')
		cy.wait(2000)
		cy.contains('New post').click()
		cy.wait(2000)
		cy.get('textarea').type('Programar en Python') 
		cy.get('.koenig-editor__editor-wrapper').type('Prueba crear un post')
		cy.contains('Publish').click()
		cy.wait(2000)
		cy.get('.gh-publishmenu-button').click()
		cy.wait(2000)
		cy.get('.modal-footer .gh-btn:not(:first-child)').click()
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
		cy.contains('Programar en Python').should('be.visible')
		cy.wait(2000)
	})

	it('Crear un post repetido y publicarlo inmediatamente',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts')
		cy.wait(2000)
		cy.contains('New post').click()
		cy.wait(2000)
		cy.get('textarea').type('Programar en Python') 
		cy.get('.koenig-editor__editor-wrapper').type('Prueba crear un post')
		cy.contains('Publish').click()
		cy.wait(2000)
		cy.get('.gh-publishmenu-button').click()
		cy.wait(2000)
		cy.get('.modal-footer .gh-btn:not(:first-child)').click()
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
		cy.wait(2000)
	})

	it('Crear un post y añadir un tag',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts')
		cy.wait(2000)
		cy.contains('New post').click()
		cy.wait(2000)
		cy.get('textarea').type('Programar en Java2') 
		cy.get('.koenig-editor__editor-wrapper').type('Prueba crear un post')
		cy.get('.settings-menu-toggle').click()
		cy.get('#tag-input').type('PruebasTag{enter}')
		cy.wait(2000)
		cy.get('.settings-menu-toggle').click()
		cy.contains('Publish').click()
		cy.wait(2000)
		cy.get('.gh-publishmenu-button').click()
		cy.wait(2000)
		cy.get('.modal-footer .gh-btn:not(:first-child)').click()
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
		cy.contains('Programar en Java2').should('be.visible')
		cy.contains('PruebasTag').should('be.visible')
		cy.wait(2000)
		cy.visit('http://localhost:2368/')
	})

	it('Editar un post',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
		cy.wait(2000)
                cy.get('.posts-list > :nth-child(2)').first().click()
		cy.get('textarea').type(' - Actualizacion de post') 
		cy.get('.koenig-editor__editor-wrapper').type('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a lacus in sem tempus')
		cy.get('.koenig-editor__editor-wrapper').type('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a lacus in sem tempus')
		cy.get('.settings-menu-toggle').click()
		cy.get('#tag-input').type('PruebasTag2{enter}')
		cy.wait(2000)
		cy.get('.settings-menu-toggle').click()
		cy.contains('Update').click()
		cy.wait(2000)
		cy.get('.gh-publishmenu-button').click()
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
	})

	it('Eliminar un post',()=>{
		cy.visit('http://localhost:2368/ghost/#/posts')
		cy.wait(2000)
                cy.get('.posts-list > :nth-child(2)').first().click()
		cy.get('.settings-menu-toggle').click()
		cy.get('form > .gh-btn > span').click()
		cy.wait(2000)
		cy.get('.modal-footer .gh-btn:not(:first-child)').click()
		cy.wait(2000)
		cy.visit('http://localhost:2368/ghost/#/posts?type=published')
	})

})

